apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pal1urgj6-nodejs 
  janus-idp.io/tekton: pal1urgj6-nodejs
  backstage.io/kubernetes-id: pal1urgj6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pal1urgj6-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml